__author__ = 'BIWMac'

class TokenType(object):
    (FEATURE_TOK, END_TOK, IF_TOK, PRINT_TOK, LOOP_TOK, UNTIL_TOK, FROM_TOK,
	IS_TOK, ID_TOK, DO_TOK, ELSE_TOK, THEN_TOK, ASSIGN_TOK, LIT_INT_TOK, ADD_TOK, SUB_TOK,
	MUL_TOK, DIV_TOK, EQ_TOK, NE_TOK, LT_TOK, LE_TOK, GT_TOK, GE_TOK, EOS_TOK,
	LEFT_PAREN_TOK, RIGHT_PAREN_TOK) =range(0,27)